CREATE TABLE [dbo].[GameServerGroup]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (newid()), 
    [PrivateKey] UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [PublicKey] UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [OwnerEmail] NVARCHAR(100) NOT NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [IsValid] BIT NOT NULL DEFAULT 1,
    PRIMARY KEY CLUSTERED ([Id] ASC)
)
